/// Platform SMS bridge — Dart side of the "lifeos/sms" MethodChannel +
/// historical import service feeding the ingestion pipeline
/// (AndroidMpesaHistoricalImportScanner / MpesaSmsIngestionWorker parity).
library;

import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:workmanager/workmanager.dart';

import '../../features/dashboard/data/providers.dart';
import '../../features/sms/ingestion/ingestion_pipeline.dart';
import '../../features/sms/ingestion/ingestion_types.dart';
import '../database/database.dart';

// ── WorkManager background task names ────────────────────────────────────────
const _kScanTask = 'lifeos.smsPeriodicScan';

/// WorkManager callback dispatcher — runs in a SEPARATE Dart isolate.
///
/// The workmanager plugin boots a headless FlutterEngine and registers all
/// autogenerated plugins; path_provider and the "lifeos/sms" MethodChannel
/// are available so readInbox() and drainRealtimeQueue() work. The Drift DB
/// is opened fresh via LifeOsDatabase.open() — WAL mode (set at schema open)
/// lets the background and foreground isolates coexist safely.
@pragma('vm:entry-point')
void smsBackgroundDispatcher() {
  Workmanager().executeTask((taskName, _) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final userId = prefs.getString('auth_user_id');
      if (userId == null || userId.isEmpty) return true;

      // Periodic scan reads the full inbox; on-resume drain only drains queue.
      final msgs = taskName == _kScanTask
          ? await SmsPlatformBridge.readInbox()
          : <RawSms>[];
      final queued = await SmsPlatformBridge.drainRealtimeQueue();
      final all = [...msgs, ...queued];
      if (all.isEmpty) return true;

      final db = await LifeOsDatabase.open();
      final holder = LifeOsDbHolder(database: db, userId: userId);
      await holder.seedAuditCounter();
      final pipeline = DefaultMpesaIngestionPipeline(holder: holder);
      try {
        await pipeline.ingestBatch(Stream.fromIterable(all));
      } finally {
        await pipeline.dispose();
        await db.close();
      }
      await prefs.setInt(
          'last_bg_scan_ms', DateTime.now().millisecondsSinceEpoch);
      return true;
    } catch (_) {
      return false; // workmanager will retry on next interval
    }
  });
}

class SmsPlatformBridge {
  static const MethodChannel _channel = MethodChannel('lifeos/sms');

  // ── Platform → Dart handler ───────────────────────────────────────────────

  /// Installs the Dart-side MethodChannel handler for platform-initiated calls
  /// and registers the WorkManager periodic inbox scan.
  ///
  /// Call once from main() after the [ProviderContainer] is created.
  ///
  /// What this wires up:
  ///  • "onSmsQueued" — fired by MainActivity.onResume() whenever the app
  ///    returns to foreground. Drains the SmsBroadcastReceiver queue and
  ///    feeds new messages through the ingestion pipeline immediately.
  ///  • WorkManager periodic task (every 3 hours) — scans the full inbox +
  ///    drains the queue even when the app is completely killed, so no SMS is
  ///    ever missed due to the app being offline at arrival time.
  static Future<void> setupRealtimeHandler(ProviderContainer container) async {
    // Handle platform → Dart calls (MainActivity fires "onSmsQueued" on every
    // onResume so queued realtime SMS are processed as soon as the app is visible).
    _channel.setMethodCallHandler((call) async {
      if (call.method == 'onSmsQueued') {
        await _drainAndIngest(container);
      }
    });

    // Initialise WorkManager with our background dispatcher then register the
    // periodic inbox scan. ExistingWorkPolicy.keep means only one copy of the
    // task is ever enqueued regardless of how many times the app restarts.
    try {
      await Workmanager().initialize(
        smsBackgroundDispatcher,
        isInDebugMode: false,
      );
      await Workmanager().registerPeriodicTask(
        _kScanTask,
        _kScanTask,
        // 3-hour cadence — Android enforces a 15-minute floor but 3 h is a
        // reasonable balance between freshness and battery use.
        frequency: const Duration(hours: 3),
        initialDelay: const Duration(minutes: 15),
        constraints: Constraints(
          networkType: NetworkType.notRequired,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresDeviceIdle: false,
        ),
        existingWorkPolicy: ExistingPeriodicWorkPolicy.keep,
        backoffPolicy: BackoffPolicy.exponential,
        backoffPolicyDelay: const Duration(minutes: 30),
      );
    } catch (_) {
      // Workmanager init failure is non-fatal — realtime drain still works.
    }
  }

  /// Drains the realtime queue and feeds new messages into the ingestion
  /// pipeline without blocking the UI. Called on every app resume.
  static Future<void> _drainAndIngest(ProviderContainer container) async {
    try {
      if (!await hasSmsPermissions()) return;
      final queued = await drainRealtimeQueue();
      if (queued.isEmpty) return;
      final db = await container
          .read(lifeOsDatabaseProvider.future)
          .timeout(const Duration(seconds: 15),
              onTimeout: () => throw StateError('db timeout'));
      final userId = await container.read(userIdProvider.future);
      final holder = LifeOsDbHolder(database: db, userId: userId);
      await holder.seedAuditCounter();
      final pipeline = DefaultMpesaIngestionPipeline(holder: holder);
      try {
        await pipeline.ingestBatch(Stream.fromIterable(queued));
      } finally {
        await pipeline.dispose();
      }
    } catch (_) {
      // Silent best-effort — failures surface on next resume or manual retry.
    }
  }

  // ── Dart → Platform calls ─────────────────────────────────────────────────

  /// Full inbox read for backfill — AndroidSmsReader parity.
  static Future<List<RawSms>> readInbox({int limit = 50000}) async {
    try {
      final rows = await _channel.invokeMethod<List<dynamic>>('readInbox', {'limit': limit});
      if (rows == null) return const [];
      return [
        for (final r in rows.cast<Map>())
          RawSms(
            id: r['id'] as int?,
            body: r['body'] as String? ?? '',
            sender: r['sender'] as String? ?? 'UNKNOWN',
            receivedAtMs: (r['timestampMs'] as num?)?.toInt() ?? 0,
          ),
      ];
    } on PlatformException {
      return const [];
    }
  }

  /// Drains realtime receiver queue captured while the engine was detached.
  static Future<List<RawSms>> drainRealtimeQueue() async {
    try {
      final rows = await _channel.invokeMethod<List<dynamic>>('drainQueue');
      if (rows == null) return const [];
      return [
        for (final r in rows.cast<Map>())
          RawSms(
            body: r['body'] as String? ?? '',
            sender: r['sender'] as String? ?? 'UNKNOWN',
            receivedAtMs: (r['timestampMs'] as num?)?.toInt() ?? 0,
          ),
      ];
    } on PlatformException {
      return const [];
    }
  }

  static Future<bool> hasSmsPermissions() async {
    try {
      return await _channel.invokeMethod<bool>('hasSmsPermissions') ?? false;
    } on PlatformException {
      return false;
    }
  }

  static Future<void> requestSmsPermissions() async {
    try {
      await _channel.invokeMethod('requestSmsPermissions');
    } on PlatformException {
      // ignore
    }
  }
}

/// Runs the full historical import: inbox → parser pool → batched writes.
///
/// [source] controls which institutions are processed:
///   'all'   → M-Pesa + Banks + Airtel (default)
///   'mpesa' → M-Pesa only (sender contains MPESA)
///   'banks' → Everything except M-Pesa and Airtel
Future<BatchIngestionResult?> runHistoricalSmsImport(
  dynamic ref, {
  String source = 'all',
}) async {
  final dbReady = await ref.read(lifeOsDatabaseProvider.future).timeout(
        const Duration(seconds: 20),
        onTimeout: () => throw StateError('db timeout'),
      );

  final userId = await ref.read(userIdProvider.future);
  if (!await SmsPlatformBridge.hasSmsPermissions()) {
    await SmsPlatformBridge.requestSmsPermissions();
    if (!await SmsPlatformBridge.hasSmsPermissions()) return null;
  }

  final messages = await SmsPlatformBridge.readInbox();
  final queued = await SmsPlatformBridge.drainRealtimeQueue();
  var all = [...messages, ...queued];
  if (all.isEmpty) return const BatchIngestionResult(imported: 0, duplicates: 0, parseFailed: 0, ignored: 0);

  // Apply source filter: check sender string for institution category.
  if (source == 'mpesa') {
    all = all
        .where((m) => m.sender.toUpperCase().contains('MPESA') ||
            m.sender.toUpperCase() == 'M-PESA')
        .toList();
  } else if (source == 'banks') {
    all = all
        .where((m) {
          final s = m.sender.toUpperCase();
          return !s.contains('MPESA') && s != 'M-PESA' &&
              !s.contains('AIRTEL') && !s.contains('TKASH');
        })
        .toList();
  }
  if (all.isEmpty) return const BatchIngestionResult(imported: 0, duplicates: 0, parseFailed: 0, ignored: 0);

  final holder = LifeOsDbHolder(database: dbReady, userId: userId);
  await holder.seedAuditCounter();
  final pipeline = DefaultMpesaIngestionPipeline(holder: holder);
  try {
    return await pipeline.ingestBatch(Stream<RawSms>.fromIterable(all));
  } finally {
    await pipeline.dispose();
  }
}
